def get_config():
    return {
        'MODEL': {
            'NAME': 'transformer',
            'TAG': 'Transformer',
            'NUM_CLASSES': 5,
            'DROP_PATH_RATE': 0.1,
            'LABEL_SMOOTHING': 0.1,
            'IMG_SIZE': 224,
            'PATCH_SIZE': 16,
            'IN_CHANS': 3,
            'EMBED_DIM': 192,
            'DEPTH': 4,
            'NUM_HEADS': 3,
            'MLP_RATIO': 4,
            'QKV_BIAS': True,
        },
        'DATA': {
            'DATA_PATH': None,
            'IMAGES_DIR': None,
            'METADATA_PATH': None,
            'CLEANED_METADATA_PATH': None,
            'IMAGE_COLUMN': None,
            'LABEL_COLUMN': None,
            'SPLIT_COLUMN': None,
            'VAL_SPLIT': None,
            'RETURN_METADATA': None,
            'BATCH_SIZE': None,
            'NUM_WORKERS': None,
            'PIN_MEMORY': None,
        },
        'TRAIN': {
            'START_EPOCH': None,
            'EPOCHS': None,
            'BASE_LR': None,
            'WEIGHT_DECAY': None,
            'CLIP_GRAD': None,
            'WARMUP_EPOCHS': None,
            'WARMUP_LR': None,
            'MIN_LR': None,
            'OPT': None,
            'SCHED': None,
        },
        'OUTPUT': None,
    }
